#Kotlin
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.parallel.tasks.in.project=false

#Gradle
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=warn
org.gradle.caching=true
org.gradle.daemon=false

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true